### PR TITLE
compatible with 4.10

### LINKED ISSUE #304: 4.10 support
The beta release of OCaml 4.10 is around the corner, and currently, the latest version of utop does not support 4.10 and fails with the following error message:
```
[ERROR] The compilation of utop failed at "/home/opam/.opam/4.10.0+trunk/bin/dune build -p utop -j 71".
-       ocamlc src/lib/.uTop.objs/byte/uTop_complete.{cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.10.0+trunk/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/lib/.uTop.objs/byte -I /home/opam/.opam/4.10.0+trunk/lib/bytes -I /home/opam/.opam/4.10.0+trunk/lib/camomile -I /home/opam/.opam/4.10.0+trunk/lib/camomile/default_config -I /home/opam/.opam/4.10.0+trunk/lib/camomile/dyn -I /home/opam/.opam/4.10.0+trunk/lib/camomile/lib_default -I /home/opam/.opam/4.10.0+trunk/lib/camomile/library -I /home/opam/.opam/4.10.0+trunk/lib/charInfo_width -I /home/opam/.opam/4.10.0+trunk/lib/findlib -I /home/opam/.opam/4.10.0+trunk/lib/lambda-term -I /home/opam/.opam/4.10.0+trunk/lib/lwt -I /home/opam/.opam/4.10.0+trunk/lib/lwt/unix -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log/core -I /home/opam/.opam/4.10.0+trunk/lib/lwt_react -I /home/opam/.opam/4.10.0+trunk/lib/mmap -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/compiler-libs -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/threads -I /home/opam/.opam/4.10.0+trunk/lib/ocplib-endian -I /home/opam/.opam/4.10.0+trunk/lib/react -I /home/opam/.opam/4.10.0+trunk/lib/result -I /home/opam/.opam/4.10.0+trunk/lib/seq -I /home/opam/.opam/4.10.0+trunk/lib/zed -intf-suffix .ml -no-alias-deps -o src/lib/.uTop.objs/byte/uTop_complete.cmo -c -impl src/lib/uTop_complete.pp.ml)
- File "src/lib/uTop_complete.ml", line 519, characters 44-48:
- Error: The function applied to this argument has type
-          ?use:bool -> loc:Location.t -> Path.t * Types.module_declaration
- This argument cannot be applied with label ~load
-       ocamlc src/lib/.uTop.objs/byte/uTop.{cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.10.0+trunk/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/lib/.uTop.objs/byte -I /home/opam/.opam/4.10.0+trunk/lib/bytes -I /home/opam/.opam/4.10.0+trunk/lib/camomile -I /home/opam/.opam/4.10.0+trunk/lib/camomile/default_config -I /home/opam/.opam/4.10.0+trunk/lib/camomile/dyn -I /home/opam/.opam/4.10.0+trunk/lib/camomile/lib_default -I /home/opam/.opam/4.10.0+trunk/lib/camomile/library -I /home/opam/.opam/4.10.0+trunk/lib/charInfo_width -I /home/opam/.opam/4.10.0+trunk/lib/findlib -I /home/opam/.opam/4.10.0+trunk/lib/lambda-term -I /home/opam/.opam/4.10.0+trunk/lib/lwt -I /home/opam/.opam/4.10.0+trunk/lib/lwt/unix -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log/core -I /home/opam/.opam/4.10.0+trunk/lib/lwt_react -I /home/opam/.opam/4.10.0+trunk/lib/mmap -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/compiler-libs -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/threads -I /home/opam/.opam/4.10.0+trunk/lib/ocplib-endian -I /home/opam/.opam/4.10.0+trunk/lib/react -I /home/opam/.opam/4.10.0+trunk/lib/result -I /home/opam/.opam/4.10.0+trunk/lib/seq -I /home/opam/.opam/4.10.0+trunk/lib/zed -intf-suffix .ml -no-alias-deps -o src/lib/.uTop.objs/byte/uTop.cmo -c -impl src/lib/uTop.pp.ml)
- File "src/lib/uTop.ml", line 345, characters 34-52:
- Error: This expression has type string Location.loc
-        but an expression was expected of type
-          Ast_helper.str_opt = string option Location.loc
-        Type string is not compatible with type string option 
-       ocamlc src/lib/.uTop.objs/byte/uTop_main.{cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.10.0+trunk/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/lib/.uTop.objs/byte -I /home/opam/.opam/4.10.0+trunk/lib/bytes -I /home/opam/.opam/4.10.0+trunk/lib/camomile -I /home/opam/.opam/4.10.0+trunk/lib/camomile/default_config -I /home/opam/.opam/4.10.0+trunk/lib/camomile/dyn -I /home/opam/.opam/4.10.0+trunk/lib/camomile/lib_default -I /home/opam/.opam/4.10.0+trunk/lib/camomile/library -I /home/opam/.opam/4.10.0+trunk/lib/charInfo_width -I /home/opam/.opam/4.10.0+trunk/lib/findlib -I /home/opam/.opam/4.10.0+trunk/lib/lambda-term -I /home/opam/.opam/4.10.0+trunk/lib/lwt -I /home/opam/.opam/4.10.0+trunk/lib/lwt/unix -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log -I /home/opam/.opam/4.10.0+trunk/lib/lwt_log/core -I /home/opam/.opam/4.10.0+trunk/lib/lwt_react -I /home/opam/.opam/4.10.0+trunk/lib/mmap -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/compiler-libs -I /home/opam/.opam/4.10.0+trunk/lib/ocaml/threads -I /home/opam/.opam/4.10.0+trunk/lib/ocplib-endian -I /home/opam/.opam/4.10.0+trunk/lib/react -I /home/opam/.opam/4.10.0+trunk/lib/result -I /home/opam/.opam/4.10.0+trunk/lib/seq -I /home/opam/.opam/4.10.0+trunk/lib/zed -intf-suffix .ml -no-alias-deps -o src/lib/.uTop.objs/byte/uTop_main.cmo -c -impl src/lib/uTop_main.pp.ml)
- File "src/lib/uTop_main.ml", line 488, characters 23-27:
- Error: This expression has type
-          loc:Location.t -> Path.t * Types.type_declaration
-        but an expression was expected of type Path.t
```

### PR DESCRIPTION
**Pull request by kandu**
This PR makes utop compatible with 4.10, resolves #304 
No significant changes, only some naming tweaks are made

### CODE REVIEW

File: src/lib/uTop_complete.ml [hunk 1]
```diff
@@ -654,9 +668,14 @@ let list_global_fields () =
     | Env.Env_constraints (summary, _) ->
         loop acc summary
 #endif
-#if OCAML_VERSION >= (4, 06, 0)
-    | Env.Env_copy_types (summary, _) ->
+#if OCAML_VERSION >= (4, 10, 0)
+    | Env.Env_copy_types summary ->
         loop acc summary
+#else
```
Comment (diml) [inline src/lib/uTop_complete.ml]: You can also use `elif` here

Comment (kandu) [reply src/lib/uTop_complete.ml]: ah, that's a cute directive
